config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  resources :categories
  get 'tags/:tag', to: 'pins#index', as: :tag
  resources :pins

  devise_for :users
  resources :users, only: [:show]
  root 'pins#index'
  get "contactus" => "pages#contactus"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user
     belongs_to :category
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
     acts_as_taggable
     validates :date, presence: true
     validates :title, presence: true
     validates :description, presence: true
     validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
 	has_many :pins

 	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  	def home
  end

	def contactus
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]



def index
    if params[:tag].present? 
      @pins = Pin.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 12)
    else
      @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
    end  
end
  def show
  end

  def new
    @pin = current_user.pins.build
    @categories = Category.all.map{|c| [ c.name, c.id ] }

  end

  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def create
    @pin = current_user.pins.build(pin_params)
    @pin.category_id = params[:category_id]
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin}
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if
    @pin.update(pin_params)
     @pin.category_id = params[:category_id]
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

        def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :date, :tag_list, :link, :title, :category)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.desc %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-wrapper">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "PostR", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Post
            <% end %>
          </li>
          <li><%= link_to "Profile", current_user %></li>
         <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
                <li><%= link_to "Log in", new_user_session_path %></li>
                </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div><!-- /.navbar-wrapper -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/navbar'%>
<div class="container">
	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
	<%= yield %>
</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class = "jumbotron center">

	<h1>Welcome to PostR</h1>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>

</div>

app/views/pages/contactus.html.erb
<h1>Contact Us</h1>
<p>Thank you for taking interest in our website!</p>

app/views/pages/home.html.erb
<div class = "jumbotron center">

	<h1>Welcome to PostR</h1>

     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %> 

app/views/pages/profile.html.erb
<h1>hello</h1>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select one!") %>
  </div>

    <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :link, "Event Page Link" %><br>
    <%= f.text_field :link, class: "form-control" %>
  </div>

  <div class="form-inline">
    <%= f.label :date %><br>
    <%= f.date_field :date, class: "form-control" %>
  </div>
</br>
  <div class="form-group">
  <%= f.label :tags, "Tags (separated by commas)"%><br />
  <%= f.text_field :tag_list %>
</div>
<div>
    <%= f.submit 'Update', :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.title %></br>
        <strong><%= pin.user.name if pin.user %></strong>
        <% pin.tags.any? %>
     <% pin.tags.each do |tag| %>
     <span class="label label-teal">
        <%= link_to tag.name, tag_path(tag.name) %>
     </span>  
<% end %>

        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
              <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @pins %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
        <%= link_to pins_path do %>
        <h1><span class="glyphicon glyphicon-arrow-left"></span></h1>
      <% end %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <h2><%= @pin.title %></h2>
    <div class="panel panel-default">
      <div class="panel-heading center">
        <div class="image-responsive">
                  <%= link_to @pin.link do %>
        <%= image_tag @pin.image.url(:medium) %>
                  <% end %>
      </div>
      </div>
      <div class= "text-center"> 
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><%= @pin.date %></p>
        <p><%= @pin.category.name %></p>
        <%= link_to "Official Event Page", @pin.link  %>
        <p> </p>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>

        <% if @pin.user == current_user %>
        <%= link_to edit_pin_path(@pin) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
        <% end %>
      </div>
        <%= link_to pins_path do %>
        <h1><span class="glyphicon glyphicon-arrow-left"></span></h1>
      <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="jumbotron">

  <h1><%= current_user.name %></h1>

</div>